### ISSUE TITLE
Feeds not showing up under tag after renaming that tag

### ISSUE THREAD

**Issue by arkadyan** [brentsimmons/NetNewsWire#1050]
Steps to reproduce (describing what I experienced, I'm not sure which bits might be more or less relevant):

1. I have an existing Feedbin account that I have set up in NNW.
1. On the Feedbin website I rename one of my tags.
1. I open NNW and it syncs. It now shows the correct, new name for the tag, but all of the feeds that were under that tag are appearing outside of it, up above the tags as if they are not tagged at all.
1. When I try dragging one (or a group) of these feeds into the tag folder in the sidebar, NNW pops up an alert saying there is a problem with my Feedbin credentials. (I am able to Refresh without trouble, so nothing else I am seeing corroborates that error message.)
1. I deleted my Feedbin account in NNW and then logged back into it. After that everything shows up correctly: the tag shows the new name and the feeds are correctly nested inside of it.

This was with NNW Version 5.0.2 (2615) on macOS 10.14.6 (18G95). Let me know if there is anything else useful I could provide (though things are in a good state for me at the moment).

**Comment by vincode-io** [comment]
@brentsimmons To fix this one, I think we are going to have to add a persistent ID to Folder.  Right now the folderID is transient.  

I recommend that we make the folderID a string and store it in the OPML file when it gets serialized.  That way we can tell if a folder has been renamed or not.  We should be able to match on ID and see that the name has changed.

**Comment by brentsimmons** [comment]
I don’t want to add anything to the OPML file that isn’t part of a standard OPML file. Could we store this in FeedMetadata.plist instead?

**Comment by vincode-io** [comment]
The relationship isn't correct for using FeedMetadata, but we could create a FolderMetadata.plist for this.  If we ever had per folder preferences, we would need it anyway.

**Comment by brentsimmons** [comment]
Sounds good — FolderMetadata.plist for me.

**Comment by vincode-io** [comment]
Should we add this one to 5.0.3?

**Comment by brentsimmons** [comment]
Yup. Good call. Added.

**Comment by kielgillard** [comment]
Since in the Feedly integration, Folders correspond to Collections, we could use a folder metadata store to save us an API request to get Collection identifiers. The use case is this. In order to update the article local statuses with their corresponding remote article statuses, the simplest and most error free way the Feedly API enables (best I can tell) is to essentially request all the unread articles only from each Collection/Folder. The app would then ensure the local articles not a member of the set of articles in the response have a read status and the others an unread status. (i.e.: read ids = local ids - remote ids) .

**Comment by brentsimmons** [comment]
Sounds like FolderMetadata.plist would be good for Feedly too.

**Comment by brentsimmons** [comment]
Before we go too far — I’m actually considering Maurice’s idea of just storing this data in the OPML file. I’ll update this bug when I’ve made a decision.

**Comment by vincode-io** [comment]
I spent some time working on this and basically we have two solutions.

Ideally, we could just change `folderID` into a string and begin persisting it.  The problem with this is migrating our existing codebase.  Because `folderID` is required and used for object equality right now, it would have to be present when we load the internal OPML and create the `Folder` objects.

Option 1)  Do a "schema migration" where we check the OPML file we are reading at application launch.  If it is Subscriptions.opml, then we would migrate it to Subscriptions_V2.opml and populate the `folderId` of the `Folder` elements.  This would require a network call to Feedbin (Feedbin accounts only) to get the correct `folderID` values.  Local accounts just use a UUID value.  The downside to this approach is its complexity.

Option 2)  Add an optional property to `Folder` called `externalID`.  This would be ignored for Local Accounts, but sync accounts could populate it as needed.  Feedbin would populate this automatically if it finds it empty to migrate existing accounts.  The downside to this one is that it is inconsistent to how we use `feedID` and `articleID`.

I'm open to other suggestions or to implementing either of the two above.

**Comment by brentsimmons** [comment]
We sort of have this in article: article.uniqueID and article.articleID.

uniqueID is gathered from the feed; articleID is either an external sync-system ID or one that we calculate (based on feedID and uniqueID).

I think the best bet is #2 — have a separate `externalID` optional for `Folder`s.

**Comment by vincode-io** [comment]
@benubois I'm having some difficulty with the Feedbin API when trying to determine if a tag has been renamed or not.  I thought there would be one of two ways to do this.

1) I expected `https://api.feedbin.com/v2/tags.json` to return back an entry that had the same `id` but a different `name`.  Instead it returns back the new `name` and a newly incremented `id`.

2) I expected `https://api.feedbin.com/v2/taggings.json ` to return a response when the tag name changed.  This doesn't seem to happen.

I verified these behaviors using NNW and curl both.

Is there another way I can detect tag name changes that I don't know about?

To work around this, I am going to detect when `https://api.feedbin.com/v2/tags.json` doesn't match what we have locally and then clear my conditional get information to force a `https://api.feedbin.com/v2/taggings.json` response.

This isn't ideal.  I end up deleting a NNW Folder and moving all the Feeds to the Account Folder (assuming they don't have any other tags) and then creating a new empty NNW Folder.  Later when we process taggings, the new NNW Folder gets populated with the new Feeds and they get removed from the Account Folder.

If scenario 1 above worked, I could just rename the Folder and not have to go through all the work of moving Feeds around.  I understand that the tag id behavior might be something you can't change, but I thought I would see anyway.

Thanks for any help you can give me here.

**Comment by vincode-io** [comment]
I'm going to close this issue out.  We have a work around that is acceptable and I am going to assume that @benubois can't change API behavior on V2 of the Feedbin API.
