### ISSUE TITLE
Mark as Starred Toolbar button always showing "Starred" status

### ISSUE THREAD

**Issue by airhead3** [brentsimmons/NetNewsWire#1057]
When any article is selected, the toolbar button for toggling Mark as Starred/Unstarred shows a filled, yellow star in the icon, regardless of whether the article is starred or unstarred. Note that the hover-over text correctly indicates the state of the article (showing "Mark as Starred" when it is currently unstarred, and "Mark as Unstarred" when it is actually starred). Articles appear to show up correctly in the Starred smart folder, and show a star in the article list, but I would expect the button to change states accordingly, as well (grayed out star if it is unstarred).

Version 5.0.2 (2615)
MacOS 10.14.6

**Comment by brentsimmons** [comment]
The toolbar buttons don’t show status graphically. There are competing and mutually exclusive expectations: show current status, or show what the command would do.

Each answer is the opposite of what some people expect! So, instead, we keep the icon the same, so that people don’t expect either. And we change the text to reflect what the command would do.
