### ISSUE TITLE
iOS: Scrolling is slow during initial sync after adding account

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1062]
My Feedbin account has a few hundred feeds. When I first set up the iOS app, and added my account, the initial sync took some time — which is totally expected. However, scrolling in the smart feeds was stuttery while the sync was going on. Something is periodically blocking the main thread. (I haven’t looked at the code yet and don’t have a theory.)

**Comment by vincode-io** [comment]
Syncing does a lot database queries and comparison work after getting the data from the sync service.  I have no doubt that is what is blocking the main thread.  I'm pretty sure that #913 is the same issue.

I recommend we move the sync code to a background thread so that it stops blocking the main thread.

**Comment by brentsimmons** [comment]
With #913 it is at least partly just the fact that we do a sync (main-thread-blocking) fetch on changing selection. But it could be other things too.

I’ll take this one — I’ll do some profiling and then look at the code.

**Comment by vincode-io** [comment]
I think your latest performance tuning put this problem to bed.

**Comment by vincode-io** [comment]
After testing it some more it does look like there is a little bit of stutter while scrolling when sync is happening.

**Comment by brentsimmons** [comment]
Got it. I’ll do some on-device profiling.

**Comment by vincode-io** [comment]
I think this problem is gone now.  I just tested with about 250 feeds.  I typically have to do around 100 paged requests for articles and process them.  Testing on my slowest device, my iPad, I didn't see any stuttering or lack of UI responsiveness while syncing my Feedbin account.

I think we can close this one out.

**Comment by brentsimmons** [comment]
Awesome! We’ll file a new bug if this ever comes up again.
