### ISSUE TITLE
iOS Feeds Screen: use same row height for all rows

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1064]
In the Feeds screen, if a feed has a long name, it wraps and creates a second line.

Instead, each row should be just one line tall, and the feed name should be truncated with ellipsis at the end.

**Comment by vincode-io** [comment]
This is an accessibility thing.  I wrap those rows because when you set dynamic type to the really big sizes, you might get one word per line if you are lucky.

We could do truncation if the content size category is small enough.  Should we check to see if the content size category is the default or smaller, then we truncate instead of wrapping?

**Comment by brentsimmons** [comment]
Good point. I’ll think about this some more.

**Comment by brentsimmons** [comment]
(My own dynamic type setting is one notch below max.)

**Comment by vincode-io** [comment]
I don't know if you've thought more about this.  I think we have two options.

1)  Always use multiline
2)  Only use multiline when `traitCollection.preferredContentSizeCategory.isAccessibilityCategory` is equal to true.

**Comment by brentsimmons** [comment]
Let’s always use multiline. Now that other alignment things are looking good, the larger rows stand out less to me.
