### ISSUE TITLE
iOS: Add a setting to suppress alert before marking all articles as read

### ISSUE THREAD

**Issue by philviso** [brentsimmons/NetNewsWire#1103]
It would be nice to be able to disable the alert that shows up every time you mark all articles as read. Asking before marking all of the articles read should be the default, but it should be controllable with a user setting.

**Comment by vincode-io** [comment]
I would like to keep the user setting stuff as minimal as possible.  Let's see if there is a way to get rid of the confirmation alert another way.

1) On the Mac app we could give you a hidden preference.  We could possibly do the same thing where we have a shortcut that can toggle hidden preferences on and off.

2) We could add some kind of "Don't show this dialog again" thing to the confirmation alert so that people can make it go away if they don't want to see it.

3) We could replace the confirmation alert with a one time alert that is educational.  It could inform the user that undo is available for Mark All and remind them what the iOS 13 undo gesture is.

Do any of those sound like a better alternative to a user setting?  Do we have any other options?

**Comment by philviso** [comment]
Talked about this with @vincode-io, and I'm gonna change the implementation to a one-time alert.
