### ISSUE TITLE
iOS: Replacing export brings up an error

### ISSUE THREAD

**Issue by sh4338** [brentsimmons/NetNewsWire#1151]
I know that you are rewriting the settings section in UIKit, and so I'm not sure if this bug will be fixed.

Exporting the same account to the same folder twice in a row brings up a dialog with three options: replace, keep both, and cancel.  If replace is picked, the following message shows up:

![EE858FB3-0B7B-4EC6-8B1D-F169D2760B99](https://user-images.githubusercontent.com/36467736/67254879-471bed00-f434-11e9-9cf9-28bd6d59ee17.jpeg)

However, this error does not show up if I already did it once (and saw the error once) *and* did not leave settings, and tried again.

**Comment by vincode-io** [comment]
I can't recreate this using the new code.  I'm not reassured though.  The code is pretty much the same as it was on the old Settings.  What I'm afraid of is that it was some iCloud flakiness that we don't have control over.

I'm going to close this one since I can't recreate it.  @sh4338 if you would do me a favor and comment on the issue if you have can still recreate it after the next TestFlight build?  I'll reopen the issue if you can still recreate it and I'll investigate further.
