### ISSUE TITLE
iOS: App hangs during launch & as sync is finishing

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1180]
Twice today I’ve launched NetNewsWire and it froze at about 80% finished with a sync to Feedbin. The app will eventually crash/be killed and then on subsequent launches, the app never finishes initialising. The Feeds screen appears, but no rows are filled and the app is unresponsive. It eventually crashes or gets killed. This behaviour persists until the device (iPhone X) is restarted.

There’s one curious thing I notice when the initial freeze occurs. The ‘Today’ and ‘Unread’ Smart Feed unread counts don’t match. They should, though, because I haven’t got any old unreads.

(I should note that I haven’t experienced it any other time this week, but that it started happening today, after updating to the latest iOS 13.2 beta last night.)

[subsequent-NetNewsWire-2019-10-26-143709.ips.beta.txt](https://github.com/brentsimmons/NetNewsWire/files/3774577/subsequent-NetNewsWire-2019-10-26-143709.ips.beta.txt)
[initialcrash-NetNewsWire-2019-10-26-143529.ips.beta.txt](https://github.com/brentsimmons/NetNewsWire/files/3774578/initialcrash-NetNewsWire-2019-10-26-143529.ips.beta.txt)

**Comment by vincode-io** [comment]
I’m pretty sure that this is the UserDefaults hanging bug.

**Comment by nostodnayr** [comment]
I wondered after I saw your #work post, but I thought I'd just file this in case it was different and to give you the unread count information.

**Comment by vincode-io** [comment]
Thanks for the report. I probably should have filed this one myself. :-)

**Comment by vincode-io** [comment]
I caught this one in the act today and was able to make some progress.  I caught it in the debugger while it was launching and hanging.  It turns out that the culprit is `BGTaskScheduler`.

For a while I thought the problem was in how we were utilizing the` UserDefaults`.  I thought this because when we wrote to the `UserDefaults` the system hung.  It turns out that we were actually getting hung in the `UserDefaults.didChangeNotification` that was trying to schedule `BGTaskScheduler`.

Now that I had the issue correct, I could actually get some traction while searching the web and came up with this.  Not very helpful, but misery loves company.

https://twitter.com/marcoarment/status/1182085151746117632?lang=en

This matches my experiences exactly.  The problem goes away on device restart.

This is clearly an Apple failure on two fronts.  First their daemon is unresponsive.  I'm assuming launchd doesn't fix this because it didn't crash.  Secondly, their `BGTaskScheduler.shared.submit` is throwable and should throw an exception when the daemon is unresponsive.

Hopefully Apple gets this fixed soon.

**Comment by vincode-io** [comment]
I think we have this one resolved.  Will reopen if anyone experiences hanging problems again.
