### ISSUE TITLE
iOS: Timeline - when empty, a phantom, empty row jumps in

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1195]
1. Tap on a folder or feed that’s empty.

2. In the timeline, watch the gridlines.

3. They’ll move a little, as it appears that a regular-sized row is added, but it’s empty. (That’s just what it looks — that’s probably not what’s actually happening.)

**Comment by vincode-io** [comment]
@brentsimmons I think this has been resolved in 13.2.  I think that empty row was supposed to be the search bar, but it wasn't showing up.  It it is now, at least on my devices.  Could you verify if this is still an issue or not?

**Comment by brentsimmons** [comment]
Yes — I see the search bar now with an empty feed.

**Comment by brentsimmons** [comment]
The question is: for any empty feed, do we want to see the search bar, when we don’t see the search bar with non-empty feeds? I think it should be consistent: you don’t see the search bar until you pull it down.

**Comment by vincode-io** [comment]
I haven't found a way to control the search bar pops in on an empty table or not.  If you watch it, you'll notice that the search bar appears a split second after the view appears.  This seems to happen after the viewDidAppear event and it will ignore if you've set the search bar as active or inactive.

I had thought that I had this under control, but that was because of the device I was testing on.  I was testing on an iPhone 6s and it wouldn't show the search bar.  Today, I noticed on my iPhone Xs that it was showing it again.

I did testing on several devices and it looks like the device has to be a specific height for the search bar to force its way in on an empty table.  Plus size devices and the newer notch devices all will force the search bar to appear with empty table rows.

While I think this behavior should be consistent, I think this is something we are going to have to live with for now.  At least we don't have the phantom empty row anymore.

**Comment by brentsimmons** [comment]
Makes sense. We can live with it.
