### ISSUE TITLE
Feeds list – Provide a base background for all favicons

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1213]
Sites which have favicons that use transparency or are just black (or both), can seem to disappear in the Feeds list when using the dark appearance for the system.

This is especially noticeable on iOS where the dark appearance background is very dark indeed. (On Mac, they're mostly visible, but it's not quite ideal.)

The NetNewsWire-generated no-favicon globe icons can also suffer from this if the generated colour is 'dark'.

Examples:
- http://feeds.feedburner.com/mcsweeneys
- https://www.omnigroup.com/blog/rss/ (The sheer cheek, I know!)

**Comment by vincode-io** [comment]
I would like to avoid adding a background to all images indiscriminately.  It's not needed and can detract from the original image in many cases.

We did a couple of fixes that make the darkmode visibility in the Feeds list better.  First, we now use the higher resolution Feed icon instead of the Favicon when available.  These tend to be lighter in color.

Second, in darkmode, we will scan an image to see if it is really dark.  If so, we will add the avatar background to the image.  It's accurate almost all of the time and provides enough contrast to view the image even it it is completely black.
