### ISSUE TITLE
iOS: Feeds list, timeline: deselect animation on navigating back - text should start out dark

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1237]
When returning to the Feeds list, or the timeline, there’s an animation where the selected row is highlighted, and the highlight fades away.

It looks like right now, the text starts white, the fade happens, and then the text is suddenly switched to black. Which makes for an odd little pop.

This makes sense, because the text is white when the row is highlighted.

However, this particular animation will work better, I think, if the text starts out black. Counter-intuitive, yes, but I think it’s correct.

**Comment by vincode-io** [comment]
I don't know if I can fix it that way.  On the iPad those views don't leave the screen sometimes.  I can't just change the color while it is off camera.

I'll try and fix that pop anther way if I can.  Maybe I can fade it from white to black as the blue fades out.

**Comment by vincode-io** [comment]
The reason that got that pop was because we sped up animations on the Feed table.  Since that is done at the layer level, the fade animation for the cells was running faster than UIKit expected.  I can fade the colors myself and get rid of the pop with no problems.

Should we speed up all table views to match the Feeds so that the fade animation is the same duration across the board now?

**Comment by brentsimmons** [comment]
Yes — sounds good.

**Comment by vincode-io** [comment]
I think I have all our vibrant transitions working with the faster animation speeds now.  I had to touch a lot of stuff, but I don't think I missed anything.
