### ISSUE TITLE
iOS: Timeline - Change Select Feed to Go to Feed, and skip the animation

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1240]
The problem with “Select Feed” is that it means selecting it in the Feeds list, but then selecting it in the Feeds list then means showing its timeline. So you kind of have to show all that with an animation, but it’s a little confusing as to what just happened.

Instead, let’s call it “Go to Feed” instead, and not use an animation. (When the person then goes back to the Feeds list from the timeline, that feed should be visible onscreen.)

**Comment by vincode-io** [comment]
I was trying to make this change and ran into an interesting problem.  If I don't animate back to the Feeds, I can't scroll the Feed to the visible area.  That's because I never have a visible area to test against.  I still have it selected, it just might not be visible when the user swipes back.

I'll keep thinking about it.  Maybe there is a way to do the targeted scrolling without visible testing and I just don't know how yet.

**Comment by brentsimmons** [comment]
Tricky! I hadn’t thought about the visibility issue.

**Comment by vincode-io** [comment]
I tried scrolling using the built in selectRow with the to middle option on `UITableView` and it suffers from the same problem that our custom scroll into view behavior does.  It can't find the middle because it isn't in the view hierarchy.

I think we'll have to keep the animation or we'll have to say in this one situation we might have a feed selected that you have to scroll to see.  Let me know what you want to do here.

**Comment by vincode-io** [comment]
Forget my previous post for now.  Something else must be going on.  I'm able to scroll the timeline for some reason while it is off camera.
