### ISSUE TITLE
iOS: Current smart folder not restored for articles on relaunch

### ISSUE THREAD

**Issue by Wevah** [brentsimmons/NetNewsWire#1241]
When an article is opened via a smart feed (I tested Today and All Unread) and the app is terminated, the article is restored when the app is relaunched, but the feed which is back one in the navigation stack is now the article's "real" feed instead of the smart one.

I didn't notice this much until 13.2 came with its overzealous background termination.

**Comment by vincode-io** [comment]
This is by design. We mark items as read immediately, so it is no longer in the unread smartfeed when the unread smartfeed is restored.  

Also it might no longer be in the Today smartfeed. We have the same problem there. 

We also can’t store the state of the smartfeed and use that on relaunch. They would be inaccurate because of new articles fetched in the background and time passing. 

The only thing we can do is restore with a direct path to the feed that the article is in. 

I’m open to hearing another design that works better. I agree that the current state restoration isn’t ideal. I just can’t figure out how to make the experience better.

**Comment by Wevah** [comment]
It didn't used to be as big of an issue, but snince iOS 13.2 when I'm going through my Today feed I'll switch out for a few minutes (sometimes even under a minute), and when I come back, iOS 13 has killed NNW—and now I'm not in the Today feed anymore.

**Comment by brentsimmons** [comment]
I strongly suspect that the app killing won’t be so aggressive in future iOS 13 releases.

Nevertheless, this needs a solution.

Would it be possible to attempt to restore to the smart feed, and fall back to the specific feed only when that article no longer appears in the smart feed?

**Comment by vincode-io** [comment]
I think that would be the best user experience.

**Comment by brentsimmons** [comment]
I think you’re right. Agreed. Let’s go with that.
