### ISSUE TITLE
iOS: Article view - remove Safari button, place Reader button where Safari button was (right side of toolbar)

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1260]
Here’s the problem: there’s enough going on in the detail view that it’s a bit distracting.

The Reader button, centered at the top of the screen, is one of the more distracting parts — and it’s hard to hit up there.

Since the Safari button isn’t so critical, let’s replace it with the Reader button. This will remove a distraction *and* make the Reader button easier to use.

**Comment by vincode-io** [comment]
This is a good change.  I made one tweak that I hope is ok.  I pushed the share button to the end of the toolbar because I was still having trouble hitting the reader button with my left hand on an iPhone Xs.

![IMG_0385](https://user-images.githubusercontent.com/16448027/68305260-f54aa800-006c-11ea-8b76-45a3cfcecfe7.jpeg)

**Comment by brentsimmons** [comment]
Cool. Good call.
