### ISSUE TITLE
iOS: Search field animation makes list view jumpy

### ISSUE THREAD

**Issue by good** [brentsimmons/NetNewsWire#1272]
When on a list of articles, like the Today view, if I drag down to see the search field, it kind of animates into view. When I scroll up a little, it animates away.

The animation throws me. I thought it was a bug the first time, because my eyes were already focused on the articles and they all jumped a bit. When I’m scrolling, especially slowly, my eyes track my movement and I can read. But then that jump happens when the search field is animating away.

[See attached video for a comparison between list view search behavior in NNW vs. Mail. ](https://github.com/brentsimmons/NetNewsWire/files/3821219/File.from.iOS.MP4.zip)

**Comment by vincode-io** [comment]
This turns out to be a regression from fixing #1238 where we stopped extending the table view rows under the navigation bar.  It seems that the search controller is jumpy when you don't extend to the top of the screen under the navigation bar.  A wild guess is that it is still doing adjustments for the status bar when it shouldn't be.

I'm going to rollback #1238 as I think this is the worst bug of the two.
