### ISSUE TITLE
iOS: Credentials navigation bar is too short

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1301]
Compare to the Account Info screen: 

![IMG_87790E8CDADD-2](https://user-images.githubusercontent.com/2190735/68989266-2f932100-0887-11ea-96a6-983616ba9068.jpeg)

**Comment by vincode-io** [comment]
This is a perplexing one.  The navigation bar is shown in compact appearance form on iPhone, but not on iPad.  The compact appearance changes to normal appearance on iPhone when rotated to landscape then back to portrait.

**Comment by vincode-io** [comment]
I'm pretty sure that this is a UIKit bug, but not 100% sure.  This seems to happen consistently when using a modal to present a modal.

I've implemented a custom navigation controller to force the navigation bar to always be 64px instead of the 56px that it can be when initially shown on an iPhone, modal in modal.  This works around the problem that we are currently experiencing, but might not always be necessary on future versions of iOS.
