### ISSUE TITLE
Perhaps a bug with the unread filter

### ISSUE THREAD

**Issue by jemostrom** [brentsimmons/NetNewsWire#1452]
I don’t know if the list of folders/feeds should hide empty folders as soon as they are empty or not but it doesn’t happen on my iPad. It takes a while before they are hidden.

**Comment by vincode-io** [comment]
This is by design.  We wait for some event that will change the Feeds list before clearing out read items.  This would be something like refreshing the Feeds or deleting a Feed.  Our thinking is that you may want to return to a folder if you accidentally tapped outside of it.  We also don't want to remove a folder that may be selected while its last article is read.

Your best bet if you want to clear off read folders is to refresh the Feeds list (you may have more feeds coming in if you've been reading for a while) or tap the filter button a couple times.
