### ISSUE TITLE
iOS: Title Text for images - the XKCD thing

### ISSUE THREAD

**Issue by NerdyTherapist** [brentsimmons/NetNewsWire#1468]
I was not able to view an image’s alt text in the iOS app.

If I’m correct and there’s no way to view it yet, I’d be happy if this feature could be added, for example by adding an option in the context menu (that appears after long pressing the image). 

As discussed in a previous issue, some feeds (like XKCD) have important alt texts in their images.

**Comment by brentsimmons** [comment]
I’m betting it’s actually a title tag rather than the alt tag. But, either way, we need a solution for this. Requires design.

**Comment by kenrachynski** [comment]
I was happy to see this in a recent test flight. However, it doesn’t always work. As in the white text at the bottom of this recent image. 

![E1029C8F-ED47-44B7-B6B9-C10DB9B4635B](https://user-images.githubusercontent.com/867597/72118958-1d29e680-3310-11ea-939e-c0c8f889c812.png)

**Comment by vincode-io** [comment]
I've added a translucent background to the label so that you will still be able to read the white text on a white image background.  It is coming in the next build.

**Comment by colons** [comment]
i am not a fan of this implementation. on ipad in landscape, it is hard to read due to the very long line length, and due to the lack of padding i feel doesn't look good. i also can't seem to to dismiss it, so it often obscures important content in a way that's not really possible to work around.

i really like how Mast and Reeder handle this; as text that appears at the top of the list of actions when you peek (press and hold) an image

![Mast's alt text strat](https://user-images.githubusercontent.com/1394710/73169073-27f7c000-40f3-11ea-8b2c-c67d5a2fb172.jpeg)

![Reeder's alt text strat](https://user-images.githubusercontent.com/1394710/73169047-16161d00-40f3-11ea-803c-7cf0d89bfc69.jpeg)

**Comment by Wevah** [comment]
There should definitely be a way to dismiss it without dismissing the image.

**Comment by stevenbedrick** [comment]
Is this fixed in today's release? I'm not seeing any alt text for today's xkcd, and maybe it's due to a lack of translucent background?

**Comment by vincode-io** [comment]
XKCD doesn’t always have a title associated with the image. That was the case with the “Business Greetings” entry.

**Comment by stevenbedrick** [comment]
Ha! Yes, it’s been forever since I noticed an xkcd _not_ having a title/alt tag that it didn’t even occur to me that that could be the explanation. Looking at a different day’s entry in the RSS feed, the text appears as appropriate. Sorry for the false alarm!

**Comment by vincode-io** [comment]
All good man!  We figured out real quick how passionate XCKD fans are about their comics.
