### ISSUE TITLE
Sidebar: rename feed by direct editing

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#156]

**Comment by danielpunkass** [comment]
I'm curious about what motivated this issue, and personally think it should be reverted. I have found myself inadvertently entering editing mode when I click on feeds in my list. I even discovered a feed named "k" ... why? Because evidently I clicked on it, starting reading the articles, and then tried to mark them all as read.

To my mind the name of a feed is a rarely altered thing. The vast majority of feeds will probably never be renamed by users. It doesn't seem like too much work to have to open an inspector to more intentionally name an item.

**Comment by brentsimmons** [comment]
The issue is, I think, that of being Mac-like — does Mac-like-ness *require* inline editing of renamable things in a source list?

If it doesn’t require it, we could remove it.

**Comment by danielpunkass** [comment]
Good question. My hunch is that for infrequently modified properties, it doesn't need to be editable. But maybe that is not a good enough reason to defy the expectation that editable things _should_ be inline editable. It's also possible I was just running into an unusual string of finding it too easy to edit them.

**Comment by justdave** [comment]
If you treat it like Finder, you can only click-to-edit if it's already highlighted and hasn't previously been clicked on in the past second or so. Which means unless you're clicking on a name that's already highlighted, it takes at least two clicks to edit. This would make it less likely to happen on accident.

**Comment by brentsimmons** [comment]
We’re using the built-in behavior and timing (of NSOutlineView), and the choice really is between that and not allowing inline editing.

**Comment by danielpunkass** [comment]
@justdave I think this is in fact how it works now, so it might be that I really have no excuse for accidentally invoking this thing ;)

**Comment by sdevore** [comment]
@danielpunkass and @justdave it seems to work the same way as the finder for me as well

**Comment by brentsimmons** [comment]
I decided to disable inline editing in the sidebar.

**Comment by danielpunkass** [comment]
Thanks for considering and making a decision on this @brentsimmons !
