### ISSUE TITLE
Misinterpreting HTML

### ISSUE THREAD

**Issue by JonathanMonahan** [brentsimmons/NetNewsWire#332]
A post on the Chromium blog at http://blog.chromium.org/2018/02/chrome-65-beta-css-paint-api-and.html renders incorrectly in Evergreen.  In Safari and Chrome it looks like this:

<img width="686" alt="screen_shot_2018-02-09_at_17 34 05" src="https://user-images.githubusercontent.com/6673350/36041960-29fb5f26-0dc2-11e8-8ea2-024687b84f64.png">

but in Evergreen the HTML code block is interpreted:

<img width="639" alt="screen_shot_2018-02-09_at_17 53 13" src="https://user-images.githubusercontent.com/6673350/36042008-5725d170-0dc2-11e8-988b-cb717144baa0.png">

**Comment by JonathanMonahan** [comment]
Another example today from the same blog - in NetNewsWire 5.0d3 (1241) it is displayed like this:
![screen_shot_2018-09-06_at_14 43 18](https://user-images.githubusercontent.com/6673350/45161308-7e551d80-b1e3-11e8-8894-410bbc640453.png)

In Chrome the page is rendered like this:
![screen_shot_2018-09-06_at_14 43 43](https://user-images.githubusercontent.com/6673350/45161329-8c0aa300-b1e3-11e8-99e0-284b516b3937.png)

Notice how the '<iframe>' text has been interpreted as a tag.  This behaviour could be mistakenly or maliciously used to produce some very nasty security problems...

**Comment by vincode-io** [comment]
The root of this problem seems to be that we are decoding the escaped HTML more than once.  In this particular case there is escaped HTML code (a textarea) that should be rendered as text, but because it is being decoded twice is being interpreted as valid HTML tags.

On a lark, I changed line 317 in RSRSSParser.m to be: 
`	return self.parser.currentStringWithTrimmedWhitespace;`

That eliminated the call to `rsparser_stringByDecodingHTMLEntities` on that line and fixed this particular issue.  I would be surprised if this is the correct fix for this problem.  It probably broke a bunch of other things.

I'm going to leave the final fix on this one to someone who can implement a less ham-handed fix for this particular problem.

**Comment by brentsimmons** [comment]
@vincode-io was correct — we were decoding too much. Fixed with a commit to RSParser.
