### ISSUE TITLE
Have alternative ways to display feeds

### ISSUE THREAD

**Issue by arzoriac** [brentsimmons/NetNewsWire#353]
Since now the majority of publications truncate the feeds or just display the headline it become a necessity to have alternative ways to read feeds. Here are three solutions to this:

1 - Display the original story, loaded inside the feed reader (i.e. the native browser of NetNewsWire 3 or NewsBlur's Story View).

2 - A parser to extract the text (as well as embedded media).

3 - An option to display just the title for certain feeds. Let's say you want to read ESPN/Nate Silver's FiveThirtyEight but the feed reader doesn't display all the interactive tables correctly so it is better to just have a glanceable headline and jump to the post on the internal/external browser.

**Comment by jjeising** [comment]
> 1 - Display the original story, loaded inside the feed reader (i.e. the native browser of NetNewsWire 3 or NewsBlur's Story View).

I would really like to see a native view, simply load the URL instead of the feed content, and maybe even implement this.

I'm still using NetNewsWire 3 with a custom theme, which works for all pages, except those blocking frames. From all more current readers I haven't found one that would support this natively.

@brentsimmons What do you think of this? Can you see this, maybe as a global view option in the beginning?

**Comment by brentsimmons** [comment]
I’ll consider it for after 1.0. There are a few things to think about — just load the page as-is? Or use something like Readability? Bears careful thought.

**Comment by arzoriac** [comment]
I believe the best option is to load the page as-is. There is a lot of use cases that favors this behavior such as sites with LaTeX rendered via MathJaX or MathML like [The n-Category Café](https://golem.ph.utexas.edu/category/), or sites with interactive features such as some posts on [FiveThirtyEight](https://fivethirtyeight.com/). With these sites I already have the full text; what I don't have is the _rendering of some elements_ such as equations, interactive media (graphs, tables, and other explorable things).

**Comment by brentsimmons** [comment]
But then should it include browser controls? Back-forward buttons, location text field, etc.? And what about content blockers? Should there be a way to temporarily widen the detail view (since lots of web pages still look bad when narrow)? What about bookmarks?

Knowing where to draw the line is the problem here, because, no matter where it’s drawn, there will be requests that the line move toward full browser functionality, which can end up eating up development time best spent on other things. (Because, after all, everybody already has a browser.)

So that’s the dilemma. :)

**Comment by arzoriac** [comment]
> But then should it include browser controls? Back-forward buttons, location text field, etc.?
Probably not.

> And what about content blockers?
Depends. SFSafariViewController uses content blockers, autofill, etc. But I think Evergreen would use WKWebView, right? In this case, I think it's just a "dumb frame" that only displays the website and every bit of functionality needs to be created for.

> What about bookmarks?
You can share sites to Pinboard, Instapaper, Pocket, and others so I think this isn't necessary.

But I concur with all you said. Implementing that functionality can be a huge time sink. Worst: people being disappointed that it isn't a full-blown browser that behaves or have X and/or Y just like every other one.

**Comment by brentsimmons** [comment]
Unfortunately, SFSafariViewController is iOS only. Sigh. So, yes, it would use a WKWebView — which means (I think) that content blockers, autofill, etc. wouldn’t be there.

**Comment by jjeising** [comment]
> But then should it include browser controls? Back-forward buttons, location text field, etc.? And what about content blockers? … What about bookmarks?

I don't think any of this would be needed. Content blocker would be nice and there is `WKContentRuleList`, but this would probably require third party support from a blocker extension.
I think all links should open in the default browser.

For me the use case is the following: I would like to get a quick look and read most articles in the reader. If the page isn't usable because of ads but still looks interesting enough its okay to open in in the browser. All other links are navigation (and would require multiple tabs) and may also be interesting for the history, so this should happen in the browser.
But I don't want to open all articles in the browser.

Without any browser like functionality (back button, etc) I think complains would be less about other missing parts and could be explained easily.

> Should there be a way to temporarily widen the detail view (since lots of web pages still look bad when narrow)?

I don't think this is necessary. Displays are generally widescreen, my current Evergreen view is about 1000px wide. Most pages optimise more and more for flexible screen layouts and mobile, so even smaller views should be fine.

As `DetailWebView` exists I imagined this as "load feed url instead of HTMLString". But I understand other issues may come with that.

**Comment by brentsimmons** [comment]
We’re mostly like to use the system that Feedbin is hosting.

**Comment by vincode-io** [comment]
This has been implemented under issue #1013.
