### ISSUE TITLE
Sharing menu: send to MarsEdit doesn’t work on Mojave

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#427]
Grrrr. Hoping Daniel has some idea what to do here.

**Comment by danielpunkass** [comment]
In my tests on Mojave Beta 9, the share to MarsEdit feature seems to be working. However, it excerpt the entire selected post, and doesn't send just a subset of the selected content, for example. Is it completely failing for you?

**Comment by brentsimmons** [comment]
Completely failing for me. Maybe only on Debug build? I haven’t tried it with a Release build.

**Comment by danielpunkass** [comment]
I'm also running a Debug build. Maybe break in the SendToMarsEditCommand class and see if you can step through to see where it fails? I wonder if it's failing to locate the target app by identifier on your system for some reason.

**Comment by brentsimmons** [comment]
About selecting the entire post — what should it do? Use the selection in the detail view?

**Comment by danielpunkass** [comment]
About selecting the entire post, yeah I think what NNW3 for instance did was just send over the selection. The MarsEdit Bookmarklet is the same.

Maybe look in the console for evidence of any errors that might pertain to the failure? Just to check, are you running MarsEdit 4.x? Not an older MarsEdit maybe getting selected somehow?

**Comment by brentsimmons** [comment]
Using MarsEdit 4.1.3. NetNewsWire is sending to the correct app, which I’ve already launched. There are no other MarsEdits on my computer.

And there’s nothing in Xcode’s console or in Console.app that appear related in any way.

**Comment by danielpunkass** [comment]
Well I'll be darned. I wonder if this is something subtle related to https://indiestack.com/2018/08/apple-events-usage-description/ ... does NetNewsWire have an Apple Events usage description? It would be interesting if adding it caused the expected prompt to allow the Apple Event sending.

I vaguely recall situations where activating works because it's "whitelisted" but then subsequent AppleEvents fail because of a lack of permission from the user.

**Comment by danielpunkass** [comment]
(this is the kind of feedback-less failure mode that a lot of apps are going to experience in Mojave unless Apple does something to change the way Apple Event rejections are handled by the system).

**Comment by brentsimmons** [comment]
It doesn’t have an Apple events usage description. I guess that’s something to look into. (I’m not totally happy with this situation.)

**Comment by danielpunkass** [comment]
FWIW @brentsimmons after I downloaded the latest official release I am able to reproduce the bug as you described it. I'll see what I can find poking around at it now that I can repo.

**Comment by danielpunkass** [comment]
I confirmed from the Console that the event is being rejected because of NetNewsWire's lack of permission: 

error	09:41:28.217422 -0400	MarsEdit	Since sending application [sess=100012 pid=7265 uid:501,501,501 g:20,20 pV:7266] is not permitted to send this AppleEvent to this process, returning an errAEEventNotPermitted reply.

I suspect adding a usage string will fix this. I'll prepare a PR.

**Comment by danielpunkass** [comment]
When I build and run NetNewsWire myself from Xcode, it works, and the console reflects:

debug	11:25:41.699869 -0400	MarsEdit	EBlg/oitm was previously approved, so allowing this event from [sess=100012 pid=10003 uid:501,501,501 g:20,20 pV:10003].

So it's kind of hard for me to test that the fix will work, but I think we should just try it and hope for the best on the next update.

**Comment by brentsimmons** [comment]
Needs testing.

**Comment by danielpunkass** [comment]
After I uploaded to the latest Version 5.0d4 (1259), I was not able to reproduce the bug any longer. Sharing with MarsEdit finally prompted me with the expected first-time dialog: 

![2018-09-07 at 9 35 pm](https://user-images.githubusercontent.com/14606/45248965-1dfad480-b2e6-11e8-97ca-6445ff0d89dd.png)
