### ISSUE TITLE
Support compression

### ISSUE THREAD

**Issue by da2x** [brentsimmons/NetNewsWire#430]
Please add gzip and brotli compression support for every network request (at least feed fetching) to reduce bandwidth costs and improve feed update speeds over a slow connection.

`Accept-Encoding: gzip, br`

**Comment by danielpunkass** [comment]
I made a trivial test monitoring traffic to scripting.com/rss.json and it looks like NetNewsWire is requesting gzip compression:

`GET /rss.json HTTP/1.1
Host: scripting.com
If-None-Match: "1fd70e8b79c5ee8be5d9aa0fb145071b"
Accept: */*
If-Modified-Since: Wed, 05 Sep 2018 14:38:16 GMT
User-Agent: NetNewsWire (macOS; RSS Reader; https://ranchero.com/netnewswire/)
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive
`

Putting aside the question of supporting brotli, is there a specific feed where you noticed that gzip compression is not being requested?
