### ISSUE TITLE
Article render bug "looks like a zine mode"

### ISSUE THREAD

**Issue by todrobbins** [brentsimmons/NetNewsWire#456]
I'm not sure what the issue is as this only showed up on one article in my feed, but here's some screen grabs and the link in question (https://kottke.org/18/09/sea-slugs-can-arm-themselves-with-venom-from-other-animals):

<img width="1392" alt="screen shot 2018-09-11 at 10 23 50 am" src="https://user-images.githubusercontent.com/158590/45376156-5a635480-b5b4-11e8-8458-b95bef184a98.png">
<img width="1280" alt="screen shot 2018-09-11 at 10 23 52 am" src="https://user-images.githubusercontent.com/158590/45376159-5afbeb00-b5b4-11e8-9ae1-202a1d5625e1.png">
<img width="1392" alt="screen shot 2018-09-11 at 10 23 58 am" src="https://user-images.githubusercontent.com/158590/45376160-5afbeb00-b5b4-11e8-9ace-1545d1220fbc.png">
<img width="1392" alt="screen shot 2018-09-11 at 10 24 17 am" src="https://user-images.githubusercontent.com/158590/45376162-5afbeb00-b5b4-11e8-8b5a-6f2c075d47aa.png">

My specs:

- MacBook Pro (Retina, Mid 2012)
  - macOS 10.13.6
  - NetNewsWire 5.0d6

**Comment by brentsimmons** [comment]
What’s the URL of the feed you’re using for Kottke?

**Comment by todrobbins** [comment]
`http://feeds.kottke.org/main`

**Comment by danielpunkass** [comment]
The way the graphics defects are drawn it looks to me less like an HTML/Web rendering issue and more like a video graphics problem on the affected Mac. It is weird though if it only affected one article in the feed. Maybe because it has an embedded video in it?

@todrobbins Are you still able to readily reproduce this? Does it persist after quitting and reopening NetNewsWire? If you have time, can you confirm whether rebooting your Mac makes any change?

Thanks!

**Comment by todrobbins** [comment]
Hard to reproduce because my work laptop was _just_ replaced 😆 

Let's close this for now since it was likely my old graphics card causing the issue.
