### ISSUE TITLE
Tabbing into the article list should ensure an article is selected

### ISSUE THREAD

**Issue by danielpunkass** [brentsimmons/NetNewsWire#558]
Version 5.0d16 (1592)

1. Select a feed in the source list that has articles.
2. Press the tab key.

Expected: the article list should be focused, and an item, probably the first unread article if any unreads, falling back to the first read article, should be selected.

Actual: the article list is selected but there is no visual feedback. You have to know to press the down arrow or other keyboard navigation to select an article.

**Comment by brentsimmons** [comment]
The fix for this created a new bug, so I’ve commented out this code for now.

If you uncomment the code, you can reproduce the new bug like this:

Select something in the sidebar. The timeline should have no selection.

Scroll the timeline view using a gesture on mouse or trackpad — don’t make it the first responder.

Click on an article in the timeline. The timeline article that gets selected isn’t the one you clicked on.

**Comment by vincode-io** [comment]
@brentsimmons Can we close this issue or is there something more to do on it?

**Comment by brentsimmons** [comment]
I just haven’t had a chance to check it out yet — I’ll do so and then close this.
