### ISSUE TITLE
Unread marker (dot) occasionally not the correct color

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#569]
<img width="93" alt="screen shot 2019-02-28 at 8 21 12 pm" src="https://user-images.githubusercontent.com/9995188/53612110-a58b1700-3b96-11e9-81cb-828a39e07982.png">

Attached is a screenshot showing that portion of my NNW window. I use Dark Mode and have Orange selected as my accent and highlight color. Most of the dots are orange, but very occasionally a feed shows with a white dot. It has been this way for two versions (1 back from the newest one which added search), I think. That's when I noticed it. It is almost always a different feed and always just one article in that feed.

**Comment by vincode-io** [comment]
This one has me baffled.  Thus far I haven't been able to replicate the issue.

I suspect that the problem is the checks for Mojave that were added to isSelected and isEmphasized in TimelineTableRowView on 2/8/19.  I can't for the life of me see how they are causing a problem though.

One way to make sure that this bug is killed is to remove the isSelected and isEmphasized checks in UnreadIndicatorView.draw.

**Comment by strangebirds** [comment]
This appeared this morning again, but I had no time to check some other conditions, and of course, now it doesn't appear. My plan was to switch to light mode and see what happened, and if it persisted, to attempt changing accent and highlight colors to see if that changed anything. I will update this when I have more information.

**Comment by strangebirds** [comment]
Another sighting! The issue persisted when changing my System Pref from Dark to Light:
<img width="131" alt="screen shot 2019-03-08 at 3 59 45 am" src="https://user-images.githubusercontent.com/9995188/54022012-2332c200-4157-11e9-9af8-4ed0ce6b400d.png">
and then another showing that the article is unread but marked with a white dot:
<img width="323" alt="screen shot 2019-03-08 at 4 00 09 am" src="https://user-images.githubusercontent.com/9995188/54022055-3a71af80-4157-11e9-9452-9dff60a7a084.png">

When I changed it back to Dark Mode the single white dot was still there. I tried changing the accent color and the highlight color (independently) and the other unread markers changed as expected.
I quit and restarted NNW and all dots were orange.

**Comment by vincode-io** [comment]
So, I spent a little more time looking at this one...

It looks like the isEmphasized and isSelected properties are still getting propagated down through to the TimelineTableCellView and eventually UnreadIndicatorView in the TimelineTableCellView.updateAppearance method.

I set a conditional breakpoint and did catch the updateAppearance method propagating true values for isEmphasized and isSelected one time.  I haven't been able to recreate it since.  I suspect that there is sometimes a timing issue between when AppKit sets those values on the row and when it calls viewDidMoveToSuperview (which calls updateAppearance).

**Comment by vincode-io** [comment]
@strangebirds The code to rectify this has hit the repository and is will be available in the next release.  I removed all the code that could possibly make the unread indicator white, so I think we are good.  Open another issue if you see this reoccur in the next release.
