### ISSUE TITLE
Thumbnail avatars change aspect ratio sometimes

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#605]
The avatar for Apple World Today, for instance, is not square, and it ends up getting squooshed horizontally in the timeline. The aspect ratio should remain the same, even though it won’t look that great. (Note how it appears in the detail view.)

![Screen Shot 2019-04-13 at 11 29 34 AM](https://user-images.githubusercontent.com/1297121/56083881-a9d66100-5ddf-11e9-93ae-0865a8d6db8c.png)

Feed URL: https://www.appleworld.today/blog?format=RSS

**Comment by vincode-io** [comment]
I just pushed the fix for this to master.  I was incorrectly setting the image size and width when creating the NSImage from the CGImage.

Unfortunately the resulting image from Apple World shrank down to 48x8 which gets disregarded in the timeline code.  You can verify with the iOS Dev Tools feed.  It also had an avatar that was getting distorted and no longer is.

https://iosdev.tools/rss.php
