### ISSUE TITLE
iOS: Timeline avatars on left

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#614]
In the timeline, the horizontal order of things should be, left to right:

read/unread/starred indicator
avatar (using generic image if needed, which we don’t have yet)
text
chevron

**Comment by brentsimmons** [comment]
Also: the left edge of the gridline should line up with the left edge of the avatar rect.

**Comment by vincode-io** [comment]
To do this I needed to create a generic avatar icon.  What I did was take an image of a globe and color mask it using Color Hash so that each globe was a different color (based on feed URL).  I also use these for the iOS generic feed icons.

![Screen Shot 2019-04-29 at 7 00 30 AM](https://user-images.githubusercontent.com/16448027/56894951-180c5c00-6a4d-11e9-8c95-306ae4b9aeaa.png)

We can change how this works if we need to.  We could do a rounded rect or circle with the first letter or two of the feed name, for example.

If we decide to keep it, we can do the same thing on desktop NetNewsWire.  We have a couple issues related to it.  #590 & #528

**Comment by brentsimmons** [comment]
I especially like color hashing. It’s possible that we’ll get a different source image to use (from Brad Ellis), but I assume it’s super easy to just replace that image.

**Comment by vincode-io** [comment]
Replacing any icon or image is super easy right now.

**Comment by vincode-io** [comment]
The timeline is redone to match the new timeline design.  The fonts are larger now that we are using dynamic type "text styles".  I like the large size now, but it took a little getting used to.

One thing that stands out is that there looks like there is a gap in the layout when the feed name is suppressed.  I'm not sure what, if anything, to do about about it.

One upside to supporting dynamic type is that the layouts and row heights are more flexible now.  I made the number of text lines configurable in the settings.  Default is 2, but you can go up to 6 if you want more information on the timeline.  6 was picked just to give you 5 different settings, but that number could be increased.
