### ISSUE TITLE
iOS: Feeds list: odd animation with chevron

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#623]
Maybe this is normal and I just didn’t realize it. But, in case it’s not normal, here’s what happens:

1. Swipe left slowly on a feed to reveal the “Rename” and “Delete” buttons. Note that the chevron is gone.
2. Don’t let up. Swipe right slowly enough so that if you let go, the row will animate back to normal.
3. Note how the chevron isn’t drawing — and then, suddenly, it animates from some location on the left back to its normal position on the right.

This interaction should work the same way it does in Mail. The chevron retains its relative position at all times.

**Comment by vincode-io** [comment]
Figuring out when that reorder control is being shown is a little tricky.  I wasn't doing it correctly and the chevron was getting hidden in the drawing code by setting its frame to zero on row edits.

That's why the chevron shot across the screen when restored.  It was getting animated going from zero to the right side.  It's fixed now.
