### ISSUE TITLE
Feedbin and Timeline: on fetching a feed, don’t fetch articles that are 1) read (unless starred) and 2) with a logical pubDate more than 3 months ago

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#665]
This is similar to the limits with the OnMyMac accounts. We don’t want NetNewsWire to be your personal backup of the web.

**Comment by vincode-io** [comment]
Are you seeing this happen on a specific feed?  The only thing we should be seeing older than 3 months are unread and starred articles.

**Comment by brentsimmons** [comment]
TidBITS, for example: http://tidbits.com/feeds/tidbits_blurb.rss

![Screen Shot 2019-05-19 at 4 29 42 PM](https://user-images.githubusercontent.com/1297121/57989684-52b55300-7a53-11e9-9f6b-831da39a4cd4.png)

**Comment by brentsimmons** [comment]
But really a whole bunch of them.

http://www.myballard.com/feed/
http://daringfireball.net/index.xml
http://inessential.com/xml/rss.xml
http://9to5mac.com/feed/
http://www.macdrifter.com/feeds/all.atom.xml
etc.

**Comment by vincode-io** [comment]
Is it possible that those were at marked as unread the first time you added the Feedbin account?  I just imported your OPML into my Feedbin account and am not seeing anything older than Feb 20th.

If you delete the Feedbin account out of NetNewsWire and add it again, do you still get the older articles?

**Comment by brentsimmons** [comment]
Yes — those were certainly all unread on initial import.

The change to make is in fetching from the database: it should not fetch read-and-unstarred articles older than three months.

**Comment by vincode-io** [comment]
We didn't used to.  We decided to go after those articles because it was throwing the unread counts off (they didn't match Feedbin's).

**Comment by brentsimmons** [comment]
If those articles are read, then it should be fine to not fetch them. (This stuff can be confused. If I’m not thinking of something, let me know!)

**Comment by brentsimmons** [comment]
When I say not-fetch — I mean not fetch from the database when updating the timeline.

**Comment by vincode-io** [comment]
Sorry, I miss read your previous message.  Let me start over.

How syncing works is we go after 3 months of history without checking the state.  At the end of that, we check for statuses (unread and starred) in the database that don't have articles.  We ask Feedbin for those specific articles.  We don't go after any articles that are read or unstarred older than 3 months.  

You have those older ones because they were unread when you added your account.  If you added the account now, you wouldn't get anything older than 3 months because you don't have any unreads older than 3 months.

To test this you can delete your NetNewsWire Feedbin account and add it again.  You shouldn't get anything older than 3 months because you have now marked those older articles as read.
