### ISSUE TITLE
FeedBin: Mark-all-read doesn’t always update sidebar unread count

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#670]
It seems to work fine with top level feeds. I’ve seen this happen with a feed inside a folder.

I kit the 'k' key (not sure if this matters) to mark-all-read. The timeline updated, but the sidebar did not.

![Screen Shot 2019-05-20 at 2 32 28 PM](https://user-images.githubusercontent.com/1297121/58053414-5062ff80-7b0c-11e9-9fef-2fbae10f8ab5.png)

**Comment by brentsimmons** [comment]
I just double-checked: it works fine with the OnMyMac account.

**Comment by vincode-io** [comment]
I'm not able to recreate this on my machine, but what I think was happening was that the status update database call wasn't completing before the unread count database query was happening.  I changed the status update query to be a sync call instead of async to try to rectify the issue.  If you are still seeing the issue after getting the latest from the repo, then we should back out the sync change and look for a different cause.

**Comment by brentsimmons** [comment]
This had to do with duplicate feeds, which are totally allowed. One of the feeds was getting updated — but not the one I was actually looking at.

The sidebar needed to check feed equality instead of pointer equality. Done.
