### ISSUE TITLE
iOS: Detail: Use JavaScript to set HTML

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#697]
The issue is performance when going to next/previous article or next unread. Ben and Daniel have both mentioned using JavaScript to set the various bits of HTML — that that’s faster than loading a new HTML page.

We should try it. (And, probably, later use this on Mac too.)

**Comment by benubois** [comment]
I tried hacking this in to an old build of Evergreen. It definitely was faster _except_ when there were images in the article. I think the sheer amount of base64 encoded image data made it slower. 

If you did do this, I think locally cached images would have to be referenced as files, rather than inserted into the document as base64 strings.

**Comment by brentsimmons** [comment]
Sounds like this might be more work than is warranted for the 5.0 release. Let’s hold it for after 5.0.
