### ISSUE TITLE
Update to latest Sparkle.framework

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#748]
Word on the street is that it handles Dark Mode.

Maybe it will also fix the bug where Check for Updates is disabled unexpectedly.

**Comment by brentsimmons** [comment]
@vincode-io Want to handle this one? I think the current Sparkle is just a binary downloaded from the project’s website. Presumably we can get just get a new one and swap it in.

**Comment by vincode-io** [comment]
Yeah, I’ll take a look at it.

**Comment by vincode-io** [comment]
I updated mac-candidate with Sparkle 1.21.3.  

Dark mode looks good on it now.  I was able to test up to the point that it tries to unarchive the app and fails.  This was because my dev cert didn't match the downloaded app signed with your cert.  This is how it should be, so I'm pretty confident updating still works.
