### ISSUE TITLE
User avatar should appear in timeline for micro.blog feeds

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#762]
This may be Feedbin-only — I’m not sure.

The Omni avatar in the article view should also appear in the timeline view.

![Screen Shot 2019-06-17 at 4 25 37 PM](https://user-images.githubusercontent.com/1297121/59643222-ada69c80-911c-11e9-898e-cbc15950eca6.png)

**Comment by brentsimmons** [comment]
Feed URL: https://micro.blog/feeds/brentsimmons.json

**Comment by vincode-io** [comment]
I can't recreate this one yet.  It doesn't look like it is specific to Feedbin.

My best guess right now is that the ImageDownloader failed (timeout?) or we lost an AvatarDidBecomeAvailable notification.

I'll try testing it under constrained network conditions to see if I can get ImageDownloader to timeout while WKWebView is still able to load the link.

**Comment by vincode-io** [comment]
Could you test this again and see what happens?  I think a networking hiccup through us off.

My hypothesis:

1) A timeline was selected
2) Timeline requested the author avatar image to load.
3) The favicon image was available from the cache, so that was loaded and used.
4) The author avatar image request failed, leaving the favicon in place.
5) The timeline cell was selected.
6) WKWebView was able to load the author avatar tag successfully.
7) We now have mismatched avatars between the timeline and detail views.

Assuming that is what happened, the workaround we have would be to click into another timeline and back again to ask for the author avatar another time.

One mitigation strategy would be to have ImageDownloader try multiple times (like 3) when it doesn't get an image back.

**Comment by brentsimmons** [comment]
Working now. Calling it closed.
