### ISSUE TITLE
Title links to <link rel="related"...>

### ISSUE THREAD

**Issue by jsit** [brentsimmons/NetNewsWire#822]
The [Daring Fireball feed](https://daringfireball.net/feeds/main) uses this markup:

```xml
<entry>
	<title>Apple Maps in iOS 13</title>
	<link rel="alternate" type="text/html" href="https://www.macstories.net/stories/apple-maps-in-ios-13-sights-set-on-google/" />
	<link rel="shorturl" type="text/html" href="http://df4.us/rq8" />
	<link rel="related" type="text/html" href="https://daringfireball.net/linked/2019/07/31/apple-maps-ios-13" />
	<id>tag:daringfireball.net,2019:/linked//6.35936</id>
	<published>2019-07-31T16:03:27Z</published>
	<updated>2019-07-31T16:06:47Z</updated>
	<author>
		<name>John Gruber</name>
		<uri>http://daringfireball.net/</uri>
	</author>
	<content type="html" xml:base="https://daringfireball.net/linked/" xml:lang="en"><![CDATA[
<p>Ryan Christoffel, writing for MacStories:</p>

<blockquote>
  <p>Timed with the spread of its first-party mapping data, Apple is giving the Maps app a big upgrade in iOS 13 that represents the company’s biggest push yet to overtake Google Maps as the world’s most trusted, go-to mapping service. Apple Maps in iOS 13 represents – if you’re in the US at least – Apple’s purest vision to date for a modern mapping service. Here’s everything that it brings.</p>
</blockquote>

<p>Comprehensive overview of what’s new, and where Apple Maps stands versus Google Maps.</p>

<div>
<a  title="Permanent link to ‘Apple Maps in iOS 13’"  href="https://daringfireball.net/linked/2019/07/31/apple-maps-ios-13">&nbsp;★&nbsp;</a>
</div>

	]]></content>
  </entry>
```

The title in the preview pane links to the `rel="related"` URL rather than the `rel="alternate"` URL. I believe this is incorrect?

**Comment by brentsimmons** [comment]
This is correct. NetNewsWire tries to find the permalink — that is, the link on the blog. This is based on experience with earlier versions: people tend to prefer the permalink.

**Comment by jsit** [comment]
Thanks for the info; is this in opposition to the Atom spec?:
https://tools.ietf.org/html/rfc4287#section-4.2.7.2

If the author of the Atom feed intends for the link to point to a different domain, shouldn't that be obeyed?

**Comment by brentsimmons** [comment]
It‘s a user experience issue, though. My experience and judgment tells me the best user experience is to use the permalink, so I do.

**Comment by bfad** [comment]
I don't expect a response or for this to change, but count me in as someone who dislikes the experience you've chosen for the following reasons:

1. As a long-time Daring Fireball reader, this is not what I'm used to at all. I'm used to the title link taking me to the linked article and the star link in the body taking me to the DF entry.

2. What you've done is removed the user experience that the feed author has selected. You are prioritizing your judgement over theirs, but it's their feed.

Again, I honestly think that John Gruber has chosen the better user experience because the whole point is that he is linking to things that others may find interesting. When a user reads the small intro and clicks the link, with John's setup that takes them to the article and lets them read right away. With your setup it requires a second click to get me to what I want to be reading.

**Comment by da2x** [comment]
@brentsimmons please reopen this issue. NetNewsWire selects the last `link` element in an `entry`. The spec allows for multiple links with different link relations. NetNewsWire doesn’t need to support all link relations, but it should select `link[rel=alternate]` instead of the last `link` element.
