### ISSUE TITLE
First search causes detail view to flash white

### ISSUE THREAD

**Issue by roelspruit** [brentsimmons/NetNewsWire#901]
Hi, first of all thanks for building a great app. I've enjoyed following its inception :)

I've noticed the following bug:
- Do a clean start of the app
- Switch to "today"
- Go to the searchbar
- Type a few letters to search for a specific article
- The right part of the screen will briefly flash white before going back to the "No selection" state.

I am on Mojave and I have Dark Mode enabled.

Here is a zipped screen recording of it happening:
[Screen Recording 2019-08-28 at 15.53.56.zip](https://github.com/brentsimmons/NetNewsWire/files/3551257/Screen.Recording.2019-08-28.at.15.53.56.zip)

**Comment by correia** [comment]
I see this flash in the main content area on launch into dark mode. 

It seems like this may be the same bug as I addressed for iOS. 

The flash for the search results web view can be avoided by "preloading" it like I did on iOS, but I don't have a solution for the main view, since we use that right away.

**Comment by brentsimmons** [comment]
Fixed in PR #932
