### ISSUE TITLE
Date parsing should be more liberal

### ISSUE THREAD

**Issue by pguyot** [brentsimmons/NetNewsWire#908]
Thank you for NetNewsWire 5.0.
A couple of feeds I subscribed to display wrong item dates.

Example 1 
https://dockets.justia.com/docket/california/candce/3:2017cv03301/312704/feed

<img width="759" alt="Screenshot 2019-08-29 at 07 46 45" src="https://user-images.githubusercontent.com/168407/63913675-47e66300-ca31-11e9-8568-1a3eefdc9037.png">

The date of every item is `/rss/channel/pubDate|lastBuildDate` which is computed by the server to be now. Yet, the interesting date is `/rss/channel/item/pubDate`.

    <pubDate>Thu, 18 Jul 2019 00:00:00 -0700</pubDate>

Example 2
https://danstonchat.com/rss.xml apparently redirecting to http://feeds.feedburner.com/bashfr

<img width="936" alt="Screenshot 2019-08-29 at 07 51 01" src="https://user-images.githubusercontent.com/168407/63913837-d824a800-ca31-11e9-9536-f727fdd0d9c7.png">

Current first `/rss/channel/item/pubDate` is

    <pubDate>2019-08-27 00:00:00</pubDate>

I haven't checked but I guess that these feeds do not respect Atom specification. However, as a result, items are wrongly sorted and displayed dates are obviously wrong. As a user, I wish NetNewsWire was more liberal in date parsing to cope with these unconforming feeds.

**Comment by brentsimmons** [comment]
The first example is just a matter of excessive whitespace in the pubDate value. Our date parser checks the length of the string as a sanity check, and that sanity check was too low at just 50 characters. Super easy fix.

The second one is trickier: it’s an Atom style date, but there should be a T character there’s a space. Because of that space, our date parser thinks it’s an RSS style date.

Our date parser could check to see if the date string (after whitespace) starts with the characters 2 and 0 first, then assume it’s an Atom style date. This fix will work for about 81 years.

**Comment by brentsimmons** [comment]
Fixed in RSParser. Did a longer-term fix that will last more than 81 years. :)
